### ISSUE TITLE
Привести все стили к единому стилю

### ISSUE THREAD

**Issue by nikolai-shabalin** [web-standards-ru/weblind.ru#45]
## font.css
В интернете рекомендуют **строки** обрамлять кавычками в независимости от местонахождения - html, css, js.

Было
```css
src:
  url(../fonts/helvetica-light.woff2) format('woff2'),
  url(../fonts/helvetica-light.woff) format('woff');
```

Стало 
```css
src:
  url('../fonts/helvetica-light.woff2') format('woff2'),
  url('../fonts/helvetica-light.woff') format('woff');
```

## nav.css
**Разброд и шатание, то есть перенос строки между селекторами, то его нет.**

Пример
```css
nav [class*="level-"].active {
  background-color: #f4f4f4;
  color: #0000fe;
}
nav [class*="level-"].active  > a {
  color: #000;
}

nav [class*="level-"].active  > a:hover {
  cursor: default;
}
```

**Селекторы с одним свойством, то в одну строку, то в несколько.**
Пример:
```css
[class*="level-"] > a {text-decoration: none;}

nav [class*="level-"].active  > a {
  color: #000;
}
```

Предлагаю все простые свойства сделать в несколько строк. У нас нет проблем с вертикальным чтением.

**якобы сортировка**
Пример
```
.menu-v {
  display: block;
  box-sizing: border-box;
  font-size: 1.3rem;
  line-height: 1.6rem;
  
  margin-bottom: 1.5rem;
}
```
`margin-bottom` зачем-то с отступом от `line-height`. Автор пытался объединить свойство по смыслу, но тогда это надо делать на протяжение всего файла/ов. Объединять свойства по смыслу хорошая идея, а вот делать отступы между группами сомнительно.

## style.css
Имеет закомментированный код. Не комментарии к коду, а закомментированный код.

не используется
```
@media (max-width: 480px) {

}
```
